/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package costlow;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shawn
 */
public class DeliveryStocks extends javax.swing.JFrame {
    private DefaultTableModel tableModel;
    Color defaultcolor, clickedcolor, blue, white;
     private static final String JDBC_URL = "jdbc:mysql://127.0.0.1:3306/cost low";
    private static final String DB_USER = "root";
    private static final String DB_PASSWORD = "";
    
    public DeliveryStocks(String username) {
        initComponents();
        
         tableModel = new DefaultTableModel(new Object[]{"Driver", "Date", "Product", "Quantity", "Measurement"}, 0);
        
        fetchUserProfile(username);
        
        showCurrentDate();
        
        defaultcolor = new Color(31,41,64);
        clickedcolor = new Color(20, 27, 45);
        blue = new Color(105,111,251);
        white = new Color(255, 255, 255);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        profilepanel = new javax.swing.JPanel();
        PROFILE = new javax.swing.JLabel();
        deliveredpanel = new javax.swing.JPanel();
        DELIVERED = new javax.swing.JLabel();
        listpanel = new javax.swing.JPanel();
        LIST = new javax.swing.JLabel();
        jSeparator54 = new javax.swing.JSeparator();
        jSeparator56 = new javax.swing.JSeparator();
        jSeparator58 = new javax.swing.JSeparator();
        jSeparator59 = new javax.swing.JSeparator();
        logoutPanel = new javax.swing.JPanel();
        LOG_OUT = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        panelswitch = new javax.swing.JLabel();
        PresentDate = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        ProfileFrame = new javax.swing.JPanel();
        ProfilePic = new javax.swing.JLabel();
        NameProfile = new javax.swing.JLabel();
        profile_ID = new javax.swing.JLabel();
        profileAddress = new javax.swing.JLabel();
        addressField = new javax.swing.JLabel();
        employeeIDField = new javax.swing.JLabel();
        DeliverFrame = new javax.swing.JPanel();
        productNameField = new javax.swing.JTextField();
        quantityField = new javax.swing.JTextField();
        measurementField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AddButton = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();
        ListFrame = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DeliveredTable = new javax.swing.JTable();
        refreshBtn = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jScrollPane2.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 600));

        jPanel6.setBackground(new java.awt.Color(20, 27, 45));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(31, 41, 64));

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/costlow/pics/logo100.png"))); // NOI18N

        profilepanel.setBackground(new java.awt.Color(31, 41, 64));

        PROFILE.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        PROFILE.setForeground(new java.awt.Color(255, 255, 255));
        PROFILE.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PROFILE.setText("PROFILE");
        PROFILE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PROFILEMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PROFILEMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                PROFILEMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout profilepanelLayout = new javax.swing.GroupLayout(profilepanel);
        profilepanel.setLayout(profilepanelLayout);
        profilepanelLayout.setHorizontalGroup(
            profilepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilepanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(PROFILE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        profilepanelLayout.setVerticalGroup(
            profilepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilepanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PROFILE, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        deliveredpanel.setBackground(new java.awt.Color(31, 41, 64));

        DELIVERED.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        DELIVERED.setForeground(new java.awt.Color(255, 255, 255));
        DELIVERED.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        DELIVERED.setText("DELIVERED");
        DELIVERED.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DELIVEREDMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DELIVEREDMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                DELIVEREDMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout deliveredpanelLayout = new javax.swing.GroupLayout(deliveredpanel);
        deliveredpanel.setLayout(deliveredpanelLayout);
        deliveredpanelLayout.setHorizontalGroup(
            deliveredpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deliveredpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DELIVERED, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        deliveredpanelLayout.setVerticalGroup(
            deliveredpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deliveredpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DELIVERED, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listpanel.setBackground(new java.awt.Color(31, 41, 64));

        LIST.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        LIST.setForeground(new java.awt.Color(255, 255, 255));
        LIST.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LIST.setText("LIST");
        LIST.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LISTMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LISTMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LISTMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout listpanelLayout = new javax.swing.GroupLayout(listpanel);
        listpanel.setLayout(listpanelLayout);
        listpanelLayout.setHorizontalGroup(
            listpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listpanelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(LIST, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        listpanelLayout.setVerticalGroup(
            listpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LIST, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator54.setBackground(new java.awt.Color(105, 111, 251));
        jSeparator54.setForeground(new java.awt.Color(105, 111, 251));

        jSeparator56.setBackground(new java.awt.Color(105, 111, 251));
        jSeparator56.setForeground(new java.awt.Color(105, 111, 251));

        jSeparator58.setBackground(new java.awt.Color(105, 111, 251));
        jSeparator58.setForeground(new java.awt.Color(105, 111, 251));

        jSeparator59.setBackground(new java.awt.Color(105, 111, 251));
        jSeparator59.setForeground(new java.awt.Color(105, 111, 251));

        logoutPanel.setBackground(new java.awt.Color(31, 41, 64));

        LOG_OUT.setBackground(new java.awt.Color(31, 41, 64));
        LOG_OUT.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        LOG_OUT.setForeground(new java.awt.Color(255, 255, 255));
        LOG_OUT.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LOG_OUT.setText("LOG OUT");
        LOG_OUT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOG_OUTMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LOG_OUTMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LOG_OUTMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout logoutPanelLayout = new javax.swing.GroupLayout(logoutPanel);
        logoutPanel.setLayout(logoutPanelLayout);
        logoutPanelLayout.setHorizontalGroup(
            logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LOG_OUT, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        logoutPanelLayout.setVerticalGroup(
            logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LOG_OUT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator4.setForeground(new java.awt.Color(105, 111, 251));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addComponent(listpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addComponent(jSeparator54)
            .addComponent(jSeparator56)
            .addComponent(jSeparator58, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator59)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deliveredpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profilepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jSeparator4)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jSeparator54, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profilepanel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jSeparator56, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deliveredpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jSeparator58, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator59, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 600));

        jPanel1.setBackground(new java.awt.Color(20, 27, 45));

        panelswitch.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        panelswitch.setForeground(new java.awt.Color(255, 255, 255));
        panelswitch.setText("PROFILE");

        PresentDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PresentDate.setForeground(new java.awt.Color(255, 255, 255));
        PresentDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PresentDate.setText("-");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("DATE:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(panelswitch, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PresentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(panelswitch, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(PresentDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        jPanel6.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 590, 70));

        ProfileFrame.setBackground(new java.awt.Color(31, 41, 64));

        ProfilePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/costlow/pics/Profile Pic.jpg"))); // NOI18N

        NameProfile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NameProfile.setForeground(new java.awt.Color(255, 255, 255));
        NameProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameProfile.setText("NAME");

        profile_ID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        profile_ID.setForeground(new java.awt.Color(255, 255, 255));
        profile_ID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        profile_ID.setText("EMPLOYEE ID:");

        profileAddress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        profileAddress.setForeground(new java.awt.Color(255, 255, 255));
        profileAddress.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        profileAddress.setText("ADDRESS:");

        addressField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addressField.setForeground(new java.awt.Color(255, 255, 255));
        addressField.setText("-");

        employeeIDField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        employeeIDField.setForeground(new java.awt.Color(255, 255, 255));
        employeeIDField.setText("-");

        javax.swing.GroupLayout ProfileFrameLayout = new javax.swing.GroupLayout(ProfileFrame);
        ProfileFrame.setLayout(ProfileFrameLayout);
        ProfileFrameLayout.setHorizontalGroup(
            ProfileFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileFrameLayout.createSequentialGroup()
                .addGroup(ProfileFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfileFrameLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(ProfileFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ProfileFrameLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(ProfileFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(profile_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(profileAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(ProfileFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        ProfileFrameLayout.setVerticalGroup(
            ProfileFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileFrameLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(ProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NameProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(ProfileFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profile_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ProfileFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profileAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", ProfileFrame);

        DeliverFrame.setBackground(new java.awt.Color(31, 41, 64));

        productNameField.setBackground(new java.awt.Color(31, 41, 64));
        productNameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productNameField.setForeground(new java.awt.Color(255, 255, 255));
        productNameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        productNameField.setBorder(null);
        productNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameFieldActionPerformed(evt);
            }
        });

        quantityField.setBackground(new java.awt.Color(31, 41, 64));
        quantityField.setForeground(new java.awt.Color(255, 255, 255));
        quantityField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantityField.setBorder(null);

        measurementField.setBackground(new java.awt.Color(31, 41, 64));
        measurementField.setForeground(new java.awt.Color(255, 255, 255));
        measurementField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        measurementField.setBorder(null);

        jSeparator1.setForeground(new java.awt.Color(105, 111, 251));

        jSeparator2.setForeground(new java.awt.Color(105, 111, 251));

        jSeparator3.setForeground(new java.awt.Color(105, 111, 251));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("QUANTITY:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("MEASUREMENT:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("PRODUCT:");

        AddButton.setBackground(new java.awt.Color(105, 111, 251));
        AddButton.setText("ADD");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/costlow/pics/logo100.png"))); // NOI18N

        javax.swing.GroupLayout DeliverFrameLayout = new javax.swing.GroupLayout(DeliverFrame);
        DeliverFrame.setLayout(DeliverFrameLayout);
        DeliverFrameLayout.setHorizontalGroup(
            DeliverFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeliverFrameLayout.createSequentialGroup()
                .addGroup(DeliverFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DeliverFrameLayout.createSequentialGroup()
                        .addGroup(DeliverFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DeliverFrameLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeliverFrameLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(DeliverFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(DeliverFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(productNameField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(measurementField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quantityField)
                            .addComponent(jSeparator1)))
                    .addGroup(DeliverFrameLayout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DeliverFrameLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        DeliverFrameLayout.setVerticalGroup(
            DeliverFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeliverFrameLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(DeliverFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DeliverFrameLayout.createSequentialGroup()
                        .addComponent(productNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(DeliverFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DeliverFrameLayout.createSequentialGroup()
                        .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(DeliverFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DeliverFrameLayout.createSequentialGroup()
                        .addComponent(measurementField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        jTabbedPane1.addTab("tab2", DeliverFrame);

        ListFrame.setBackground(new java.awt.Color(31, 41, 64));

        DeliveredTable.setBackground(new java.awt.Color(20, 27, 45));
        DeliveredTable.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        DeliveredTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DeliveredTable.setForeground(new java.awt.Color(255, 255, 255));
        DeliveredTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "DRIVER", "DATE", "PRODUCT", "QUANTITY", "MEASUREMENT"
            }
        ));
        jScrollPane1.setViewportView(DeliveredTable);

        refreshBtn.setBackground(new java.awt.Color(105, 111, 251));
        refreshBtn.setText("REFRESH");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ListFrameLayout = new javax.swing.GroupLayout(ListFrame);
        ListFrame.setLayout(ListFrameLayout);
        ListFrameLayout.setHorizontalGroup(
            ListFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refreshBtn)
                .addGap(219, 219, 219))
        );
        ListFrameLayout.setVerticalGroup(
            ListFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListFrameLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(refreshBtn)
                .addGap(35, 35, 35))
        );

        jTabbedPane1.addTab("tab3", ListFrame);

        jPanel6.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 540, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  
    private void fetchUserProfile(String username) {// Connect to the database
        try (Connection connection = DriverManager.getConnection(JDBC_URL,DB_USER, DB_PASSWORD)) {
            // Query to retrieve user information based on username
            String query = "SELECT * FROM employee_account WHERE username = ?";
            try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
                preparedStatement.setString(1, username);
                ResultSet resultSet = preparedStatement.executeQuery();

                // Display user information in the profile frame
                if (resultSet.next()) {
                    String name = resultSet.getString("name");
                    int id = resultSet.getInt("id");
                    String address = resultSet.getString("address");

                    NameProfile.setText(name);
                    employeeIDField.setText(String.valueOf(id));
                    addressField.setText(address);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
     private void showCurrentDate() {
        // Get the current date
        LocalDate currentDate = LocalDate.now();

        // Format the date as a string
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("MM-dd-yyyy");
        String formattedDate = currentDate.format(formatter);

        // Update the JLabel with the formatted date
        PresentDate.setText(formattedDate);
    }
    
    private void productNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameFieldActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
         saveToDatabase();
    }//GEN-LAST:event_AddButtonActionPerformed
    
    private void saveToDatabase() {
        String name = NameProfile.getText();
        String driver_id = employeeIDField.getText();
        String date = PresentDate.getText();
        String productName = productNameField.getText();
        String quantity = quantityField.getText();
        String measurement = measurementField.getText();

        try (Connection connection = DriverManager.getConnection(JDBC_URL, DB_USER, DB_PASSWORD)) {
            // SQL query to insert data into the database
            String sql = "INSERT INTO delivered_products (driver_id, driver_name, DATE, product_name, quantity, measurement) VALUES (?, ?, ?, ?, ?, ?)";

            try (PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
                preparedStatement.setString(1, driver_id);
                preparedStatement.setString(2, name);
                preparedStatement.setString(3, date);
                preparedStatement.setString(4, productName);
                preparedStatement.setString(5, quantity);
                preparedStatement.setString(6, measurement);

                // Execute the SQL query
                preparedStatement.executeUpdate();
                JOptionPane.showMessageDialog(
                        this,
                        "PRODCT ADDED.",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(
                        this,
                        "PEODUCT IS NOT ADDED.",
                        "ERROR",
                        JOptionPane.INFORMATION_MESSAGE);
        }
        productNameField.setText("");
        quantityField.setText("");
        measurementField.setText("");
    }
    
    private void PROFILEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PROFILEMouseClicked
        jTabbedPane1.setSelectedIndex(0);
        
        panelswitch.setText("PROFILE");
    }//GEN-LAST:event_PROFILEMouseClicked

    private void DELIVEREDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELIVEREDMouseClicked
        jTabbedPane1.setSelectedIndex(1);
        
        panelswitch.setText("DELIVERED");
    }//GEN-LAST:event_DELIVEREDMouseClicked

    private void LISTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LISTMouseClicked
        jTabbedPane1.setSelectedIndex(2);
        
        panelswitch.setText("LIST");
    }//GEN-LAST:event_LISTMouseClicked

    private void PROFILEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PROFILEMousePressed
        profilepanel.setBackground(clickedcolor);
        deliveredpanel.setBackground(defaultcolor);
        listpanel.setBackground(defaultcolor);
        logoutPanel.setBackground(defaultcolor);
        
        PROFILE.setForeground(blue);
         DELIVERED.setForeground(white);
         LIST.setForeground(white);
         LOG_OUT.setForeground(white);
    }//GEN-LAST:event_PROFILEMousePressed

    private void PROFILEMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PROFILEMouseReleased
        profilepanel.setBackground(defaultcolor);
    }//GEN-LAST:event_PROFILEMouseReleased

    private void DELIVEREDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELIVEREDMousePressed
        profilepanel.setBackground(defaultcolor);
        deliveredpanel.setBackground(clickedcolor);
        listpanel.setBackground(defaultcolor);
         logoutPanel.setBackground(defaultcolor);
        
         PROFILE.setForeground(white);
         DELIVERED.setForeground(blue);
         LIST.setForeground(white);
         LOG_OUT.setForeground(white);
    }//GEN-LAST:event_DELIVEREDMousePressed

    private void DELIVEREDMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELIVEREDMouseReleased
         deliveredpanel.setBackground(defaultcolor);
    }//GEN-LAST:event_DELIVEREDMouseReleased

    private void LISTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LISTMousePressed
        profilepanel.setBackground(defaultcolor);
        deliveredpanel.setBackground(defaultcolor);
        listpanel.setBackground(clickedcolor);
        logoutPanel.setBackground(defaultcolor);
        
        PROFILE.setForeground(white);
         DELIVERED.setForeground(white);
         LIST.setForeground(blue);
         LOG_OUT.setForeground(white);
    }//GEN-LAST:event_LISTMousePressed

    private void LISTMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LISTMouseReleased
        listpanel.setBackground(defaultcolor);
    }//GEN-LAST:event_LISTMouseReleased

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        String driver_id = employeeIDField.getText();
        
        dataRetrieval(driver_id);
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void dataRetrieval(String driver_id) {
    // SQL query with JOIN and WHERE to retrieve data based on EmployeeId
    String sql = "SELECT dp.driver_name, dp.DATE, dp.product_name, dp.quantity, dp.measurement " +
                 "FROM delivered_products dp " +
                 "JOIN employee_account ea ON dp.driver_id = ea.id  " +
                 "WHERE dp.driver_id = ?";

    try (Connection connection = DriverManager.getConnection(JDBC_URL, DB_USER, DB_PASSWORD);
         PreparedStatement preparedStatement = connection.prepareStatement(sql)) {

        // Set the parameter in the PreparedStatement
        preparedStatement.setString(1, driver_id);

        // Execute the query
        try (ResultSet resultSet = preparedStatement.executeQuery()) {
            // Clear existing data in the table model
            tableModel.setRowCount(0);

            // Populate the model with retrieved data
            while (resultSet.next()) {
                String driverName = resultSet.getString("driver_name");
                String date = resultSet.getString("date");
                String productName = resultSet.getString("product_name");
                String quantity = resultSet.getString("quantity");
                String measurement = resultSet.getString("measurement");

                tableModel.addRow(new Object[]{driverName, date, productName, quantity, measurement});
            }

            // Set the model to the JTable
            DeliveredTable.setModel(tableModel);
        }

    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error retrieving data from the database.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
    
    private void LOG_OUTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOG_OUTMousePressed
       profilepanel.setBackground(defaultcolor);
        deliveredpanel.setBackground(defaultcolor);
        listpanel.setBackground(defaultcolor);
        logoutPanel.setBackground(clickedcolor);
        
        PROFILE.setForeground(white);
         DELIVERED.setForeground(white);
         LIST.setForeground(white);
         LOG_OUT.setForeground(blue);
    }//GEN-LAST:event_LOG_OUTMousePressed

    private void LOG_OUTMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOG_OUTMouseReleased
       logoutPanel.setBackground(defaultcolor);
    }//GEN-LAST:event_LOG_OUTMouseReleased

    private void LOG_OUTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOG_OUTMouseClicked
         int confirmResult = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to log out?",
            "Logout Confirmation",
            JOptionPane.YES_NO_OPTION);

    if (confirmResult == JOptionPane.YES_OPTION) {
        
        this.setVisible(false);
       new StartPanel().setVisible(true);
        }
       
    }//GEN-LAST:event_LOG_OUTMouseClicked
    
    

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliveryStocks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliveryStocks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliveryStocks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliveryStocks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliveryStocks(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel DELIVERED;
    private javax.swing.JPanel DeliverFrame;
    private javax.swing.JTable DeliveredTable;
    private javax.swing.JLabel LIST;
    private javax.swing.JLabel LOG_OUT;
    private javax.swing.JPanel ListFrame;
    private javax.swing.JLabel NameProfile;
    private javax.swing.JLabel PROFILE;
    private javax.swing.JLabel PresentDate;
    private javax.swing.JPanel ProfileFrame;
    private javax.swing.JLabel ProfilePic;
    private javax.swing.JLabel addressField;
    private javax.swing.JPanel deliveredpanel;
    private javax.swing.JLabel employeeIDField;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator54;
    private javax.swing.JSeparator jSeparator56;
    private javax.swing.JSeparator jSeparator58;
    private javax.swing.JSeparator jSeparator59;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel listpanel;
    private javax.swing.JPanel logoutPanel;
    private javax.swing.JTextField measurementField;
    private javax.swing.JLabel panelswitch;
    private javax.swing.JTextField productNameField;
    private javax.swing.JLabel profileAddress;
    private javax.swing.JLabel profile_ID;
    private javax.swing.JPanel profilepanel;
    private javax.swing.JTextField quantityField;
    private javax.swing.JButton refreshBtn;
    // End of variables declaration//GEN-END:variables
}
